apiVersion: v1
kind: Service
metadata:
  name: k8spoc-webapi
  namespace: {{ .Values.instance }}-{{ .Values.phase }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8spoc-webapi    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spoc-webapi
  namespace: {{ .Values.instance }}-{{ .Values.phase }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8spoc-webapi
  template:
    metadata:
      labels:
        app: k8spoc-webapi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os 
                operator: In
                values:
                - linux
      containers:
      - name: k8spoc-webapi
        image: acrawdemo.azurecr.io/k8spoc-webapi:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: aw-acr-demo-secret