apiVersion: v1
kind: Secret
metadata:
  name: k8spoc-secrets
type: Opaque
# Use data for base64 encoded values.
data:
  SECRET_SETTING: {{ .Values.appSecrets.SECRET_SETTING | b64enc }}
  ANOTHER_SECRET_SETTING: {{ .Values.appSecrets.ANOTHER_SECRET_SETTING | b64enc }}
