apiVersion: v1
kind: ConfigMap
metadata:
  name: k8spoc-config
data:
  NON_SECRET_SETTING: {{ .Values.appConfig.NON_SECRET_SETTING }}
  ANOTHER_SETTING: {{ .Values.appConfig.ANOTHER_SETTING }}
  WEB_API_HOST: {{ .Values.appConfig.WEB_API_HOST }}