{{- if .Values.installOptions.installConsole }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spoc-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8spoc-console
  template:
    metadata:
      labels:
        app: k8spoc-console
    spec:
      # Ensure that this is only deployed to a Linux node.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os 
                  operator: In
                  values:
                  - linux
      containers:
      - name: k8spoc-console
        # Ensure we're pulling the correct image version by appending the chart app version.
        image: acrawdemo.azurecr.io/k8spoc-console-linux:{{ $.Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        # This will map each ConfigMap and app secrets value to an environment variable.
        envFrom:
        - configMapRef:
            name: k8spoc-config
            optional: true 
        - secretRef:
            name: k8spoc-secrets
      imagePullSecrets:
        - name: acr-docker-secret
{{- end }}      
