apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spoc-consoleapiclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8spoc-consoleapiclient
  template:
    metadata:
      labels:
        app: k8spoc-consoleapiclient
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os 
                operator: In
                values:
                - linux
      containers:
      - name: k8spoc-consoleapiclient
        image: acrawdemo.azurecr.io/k8spoc-consoleapiclient:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: k8spoc-config
            optional: true 
      imagePullSecrets:
      - name: acr-docker-secret
