{{- if .Values.installOptions.installWindowsConsole }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spoc-console-win
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8spoc-console-win
  template:
    metadata:
      labels:
        app: k8spoc-console-win
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          #  Target Windows nodes.
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os 
                operator: In
                values:
                - windows
      containers:
      - name: k8spoc-console
        image: acrawdemo.azurecr.io/k8spoc-console-win:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: k8spoc-config
            optional: true 
        - secretRef:
            name: k8spoc-secrets
      imagePullSecrets:
        - name: acr-docker-secret
{{ end }}
