# $jsonData = kubectl get secret acr-docker-secret --namespace k8spoc-test-dev -o jsonpath='{.data}'
# $json = ConvertFrom-Json -InputObject $jsonData
# $json.psobject.properties[".dockerconfigjson"].Value
# $bytes = [Convert]::FromBase64String($json.psobject.properties[".dockerconfigjson"].Value) 
# $dockerConfigData = ConvertFrom-Json -InputObject (-join ($bytes -as [char[]]))
# $dockerConfigData.auths.psobject.properties["acrawdemo.azurecr.io"].Value.password
# -join ([Convert]::FromBase64String($dockerConfigData.auths.psobject.properties["acrawdemo.azurecr.io"].Value.auth) -as [char[]])

apiVersion: v1
kind: Secret
metadata:
  name: acr-docker-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
