# $Env:KEY_FILE = ".\tls.key"
# $Env:CERT_FILE = ".\tls.crt"
# $Env:HOST = "*.demo.local"
# $Env:CERT_NAME = "kbastow-local-cert"
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $Env:KEY_FILE -out $Env:CERT_FILE -subj "/CN=$Env:HOST/O=$Env:HOST" -addext "subjectAltName = DNS:$Env:HOST"
# kubectl create secret tls $Env:CERT_NAME --key $Env:KEY_FILE --cert $Env:CERT_FILE
# [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($Env:KEY_FILE))
# [System.IO.File]::WriteAllText("$Env:KEY_FILE.b64", [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($Env:KEY_FILE)))
# [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($Env:CERT_FILE))
# [System.IO.File]::WriteAllText("$Env:KEY_FILE.b64", [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($Env:CERT_FILE)))

apiVersion: v1
kind: Secret
metadata:
  name: webapi-tls-cert
data:
  tls.crt: {{ .Values.ingress.tlsCert.cert }}
  tls.key: {{ .Values.ingress.tlsCert.key }}
type: kubernetes.io/tls
