apiVersion: v1
kind: Service
metadata:
  name: k8spoc-webapi
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8spoc-webapi    
