# helm package k8spoc
# helm repo index k8spoc-charts --url https://johnbastow.github.io/k8spoc-charts
# helm repo list
# helm repo update 
# helm search repo -l --regexp k8spoc-charts\/k8spoc


# Create with new namespace and new credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --set 'imageRegistryCredentials.username=<client-id>' --set 'imageRegistryCredentials.password=<client-secret>' --create-namespace

# Create with values in test-values.yaml file.
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --values ./test-values.yaml --create-namespace

# Create with existing namespace and new credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --set 'imageRegistryCredentials.username=<client-id>' --set 'imageRegistryCredentials.password=<client-secret>'

# Create with existing namespace and existing credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one

# helm list --all-namespaces
# helm list --namespace k8spoc-test-one
# helm uninstall k8spoc --namespace k8spoc-test-one
# kubectl delete namespace k8spoc-test-one

apiVersion: v2
name: k8spoc
version: 0.0.10
#kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: POC of K8s implementation
type: application
keywords:
  - A list of keywords about this project (optional)
home: https://johnbastow.github.io
# sources:
#   - A list of URLs to source code for this project (optional)
# dependencies: # A list of the chart requirements (optional)
#   - name: The name of the chart (nginx)
#     version: The version of the chart ("1.2.3")
#     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
#     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#     tags: # (optional)
#       - Tags can be used to group charts for enabling/disabling together
#     import-values: # (optional)
#       - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
#     alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: John Bastow
    # email: The maintainers email (optional for each maintainer)
    # url: A URL for the maintainer (optional for each maintainer)
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
# appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
deprecated: false
# annotations:
#   example: A list of annotations keyed by name (optional).