# helm package k8spoc --destination .\k8spoc-charts
# helm repo index k8spoc-charts --url https://johnbastow.github.io/k8spoc-charts
# helm repo list
# helm repo update 
# helm search repo -l --regexp k8spoc-charts\/k8spoc


# Install/Upgrade from local file version of package.
# helm upgrade --install k8spoc ./k8spoc-charts/k8spoc-0.0.10.tgz --namespace k8spoc-one --values ./test-values/test-values.yaml --dry-run

# Create with new namespace and new credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --set 'imageRegistryCredentials.username=<client-id>' --set 'imageRegistryCredentials.password=<client-secret>' --create-namespace

# Create with values in test-values.yaml file.
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --values ./test-values.yaml --create-namespace

# Create with existing namespace and new credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one --set 'imageRegistryCredentials.username=<client-id>' --set 'imageRegistryCredentials.password=<client-secret>'

# Create with existing namespace and existing credentials
# helm upgrade --install k8spoc k8spoc-charts/k8spoc --namespace k8spoc-test-one

# helm list --all-namespaces
# helm list --namespace k8spoc-test-one
# helm uninstall k8spoc --namespace k8spoc-test-one
# kubectl delete namespace k8spoc-test-one

apiVersion: v2
name: k8spoc
# The version of the Helm Chart.  May be different than the version of the app it's deploying
version: 0.0.11
description: POC of K8s implementation
type: application
keywords:
  - K8s
  - Kubernetes
  - POC
  - Windows
home: https://johnbastow.github.io
sources:
  - https://github.com/johnbastow/K8sPoc
maintainers: # (optional)
  - name: John Bastow
    # email: The maintainers email (optional for each maintainer)
    url: https://john.thebastows.com/
# The version of the app. A good purpose for this is to identify the correct image version.
appVersion: "0.0.2"
deprecated: false
