# kubectl apply -f kube-secrets.yaml
# kubectl get secrets
# kubectl delete secret k8spoc-secrets

apiVersion: v1
kind: Secret
metadata:
  name: k8spoc-secrets
type: Opaque
# Use data for base64 encoded values.
data:
  SECRET_SETTING: YWJpdG1vcmVzZWNyZXQ=
  ANOTHER_SECRET_SETTING: cmVhbGx5c2VjcmV0
# Use stringData for plaintext values.
# NOTE - This is not recommended by the K8s documentation.
# stringData:
#   SECRET_SETTING: abitmoresecret
#   ANOTHER_SECRET_SETTING: reallysecret