# kubectl apply -f kube-deployment-win.yaml
# kubectl get pods
# kubectl logs <pod-name> --follow
# kubectl delete deployment k8spoc-consoleapiclient-win

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spoc-consoleapiclient-win
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8spoc-consoleapiclient-win
  template:
    metadata:
      labels:
        app: k8spoc-consoleapiclient-win
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          #  Target Windows nodes.
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os 
                operator: In
                values:
                - windows
      containers:
      - name: k8spoc-consoleapiclient
        image: acrawdemo.azurecr.io/k8spoc-consoleapiclient-win:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: aw-acr-demo-secret
